### ISSUE TITLE
Trouble getting version statement to work

### ISSUE THREAD

**Issue by VFAndrew** [reindert-vetter/api-version-control#10]
https://github.com/reindert-vetter/api-version-control/blob/4f7c46a2aeae0189fa92d2aee363a6eb8c586a7d/src/Collection/MiddlewareCollection.php#L81

Getting exception `Attempt to assign property "permit" on string` when I am trying to implement a test version statement.

**Comment by VFAndrew** [comment]
added `$pipe = new $pipe();` before line 81 and also in file ApiVersionControl.php I reordered the chaining to `->filterByVersionCompare()
            ->permitVersionStatement()`
            
            it now seems to work as intended. I am on php8.1

**Comment by reindert-vetter** [comment]
Thanks! Feel free to make a pull request. Otherwise I will process it after work.

**Comment by reindert-vetter** [comment]
@VFAndrew 

> added $pipe = new $pipe(); before line 81 and also in file ApiVersionControl.php

I was able to reproduce your error and solve it in PR https://github.com/reindert-vetter/api-version-control/pull/11

> I reordered the chaining to ->filterByVersionCompare() ->permitVersionStatement()

What was that necessary for? Is the above fix sufficient for you?

**Comment by VFAndrew** [comment]
> @VFAndrew
> 
> > added $pipe = new $pipe(); before line 81 and also in file ApiVersionControl.php
> 
> I was able to reproduce your error and solve it in PR #11
> 
> > I reordered the chaining to ->filterByVersionCompare() ->permitVersionStatement()
> 
> Do you remember what it was for? Is the above fix sufficient for you?

Originally when  `->permitVersionStatement()` was run before `->filterByVersionCompare()` The VersionStatement $permit would be set to true always regardless of matched version. 

When I put  `->filterByVersionCompare()` before `->permitVersionStatement()` my version would be filtered before the statement $permit was set to true.

**Comment by reindert-vetter** [comment]
That is actually quite true indeed. Thanks for debugging!

There you have it; even though I have small unit tests for everything, I haven't fully tested everything yet.

**Comment by VFAndrew** [comment]
My pleasure. Thanks for providing an elegant way to API version control. Out of all the designs I researched this one seems to be the most forward thinking.

**Comment by reindert-vetter** [comment]
Thank you. It surprised me at the time that there weren't many solutions for it. Are you familiar with other packages?

In my opinion, it was the only way to support multiple versions with 1 controller.

**Comment by reindert-vetter** [comment]
Fixed in [2.1.6](https://github.com/reindert-vetter/api-version-control/releases/tag/2.1.6).
